name: packaging

on:
  push:
    branches:
      - main
      - dev/*

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assign version for dev
        if: contains(github.ref, 'dev')
        run: 
          npm version prerelease --preid=dev
      - name: Assign version for main
        if: contains(github.ref, 'main')
        run: 
          npm version prerelease --preid=alpha
      - name: Package VS code extension
        run: |
          npm install
          npm run package
      - name: Archive vsix file
        uses: actions/upload-artifact@v2
        with:
          name: darkturquiose-extension
          path: ./*.vsix
